### ISSUE TITLE
Repo reorganization

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/iobox#9]
Several things have crept into the project structure that weren't intended:
- `sql2dams` specific content at the root of the project (e.g., setup.py, MANIFEST, etc.)
- `beanbag-profile.json` at the top level
- `PROJECT_samples` directories for GPCR and BDDS

We need to decide how this repo should be organized and I suggest 2 alternatives for discussion:
1. split this repo into several repo, 1 per tool (e.g., sql2bag, xml2bag,...)
2. or consolidate the repo into a unified project structure with a single `setup.py` to build them together.

I am somewhat in favor of option 2 more than option 1. My only reservation is whether we have Microsoft Windows (non-portable) specific dependencies/requirements in the _sql2dams_ repo.

For discussion: @mikedarcy @svoinea @bugacov @carlkesselman @karlcz

**Comment by mikedarcy** [comment]
The `PROJECT_samples` are temporary and I don't think anyone expected them to stay in the repo forever.  They are there to facilitate testing during early development. I intend to move my BDDS samples out once I get the basic unit tests in place.  In the meantime I think that as long as we aren't putting project sensitive data in there and there is an understanding that they will go away eventually, then it isn't a big deal.

As far as reorganizing the repo I would actually like to see a combination of 1 and 2.  I think that the 'core' set of tools, i.e., dams2bag and bag2dams should be split (or remain in this repo while pruning out others) and the tools that may wrap or depend on them should be moved into another repo or individual repos.  I also favor this approach because I would like to create an ERMrest client access library in the 'core' that is shared by the other core modules and any other upstream dependencies.

I think `beanbag-profile.json` needs to be iterated on from a design perspective based on experiences in working with the BagIt API.  At the very least all references to 'beanbag' should be removed.

**Comment by mikedarcy** [comment]
Also if we are cleaning up the repo why not get rid of the deprecated stuff.  Or alternatively why don't we create a new set of repos that encapsulate the tools better as mentioned above.  Or are we married to the iobox name/repo structure?

**Comment by robes** [comment]
I would argue that the `PROJECT_samples` should be organized in `samples/PROJECT` if they apply across all tools or should be in per-tool `samples` subdirectories if they are used to test on a per-tool basis.

I would agree with your second point if you are saying that the `this2that` tools belong in this repo as the ‘core’ set of tools along with some ‘common’ libraries such as the ERMrest client lib you are proposing.

If the `beanbag-profile.json` is just an example, then it simply doesn’t belong sitting in the root of the repo and should be under the ‘bag’ doc section. If it is used for validating our bags then it may belong in the root of the repo.

**Comment by bugacov** [comment]
The thing I've been struggling with in terms of reorganization is how and
where to put the stuff the actual tools that we will be creating for each
project. In my case I needed a 2-steps tool with sql2bag and bag2dams that
I called sql2dams and packaged it there at the top level for
lack of other place to do it. The other issue is what Mike already
mentioned, the need to share libraries. It'd be great if we can reorganize
it
thinking on the creations of these tools and their
distribution/installation in different platforms.
Thanks,
Alejandro.

**Comment by mikedarcy** [comment]
@robes 
I actually feel that any project-specific samples should not be in this repo.  We can have project specific repos for that.  

Generic samples would be nice if we want to provide them, but I also feel that properly written, generic unit test configurations and sample input would be functionally equivalent to having a "samples" dir.  I am not opposed to having extra samples if needed (provided they are generic).

The python bagit library we are currently using does not provide any sort of bag validation against a bag-profile, so this is something we would have to write for ourselves.  In the short term I think moving it to the bag doc dir is the right way to go.

**Comment by robes** [comment]
We should get rid of the deprecated stuff as soon as we’ve plucked anything useful from it. By now it has probably exceeded its usefulness.

Re: creating repos, I think we need to decide whether we want to have a bunch of single-file repos (okay maybe 2-3 files per repo). It might make more sense to consolidate this repo structure into a single src/ tree and bin/ tree and single setup.py to build it all. If that were the case, then IMO `iobox` is the right name for it.

**Comment by robes** [comment]
> On Sep 3, 2015, at 1:25 PM, bugacov notifications@github.com wrote:
> 
> The thing I've been struggling with in terms of reorganization is how and
> where to put the stuff the actual tools that we will be creating for each
> project. In my case I needed a 2-steps tool with sql2bag and bag2dams that
> I called sql2dams and packaged it there at the top level for
> lack of other place to do it.

I would argue that should be such a small bash file that it shouldn’t need a setup.py of its own. If we consolidate the repo, that’s possible. I think another argument in favor of consolidation.

**Comment by robes** [comment]
Right, I totally agree. There should be no project specific content of any type in this repo.

**Comment by mikedarcy** [comment]
I'm ultimately okay with an `iobox` monolithic repo.  The only alternative that has any appeal to me is having `iobox` be a core repo and then maybe having an `iobox-tools` where higher level apps are constructed.

**Comment by carlkesselman** [comment]
I don’t see sql2bag as being project specific…..

Carl

From: bugacov
Reply-To: informatics-isi-edu/iobox
Date: Thursday, September 3, 2015 at 1:25 PM
To: informatics-isi-edu/iobox
Cc: Carl Kesselman
Subject: Re: [iobox] Repo reorganization (#9)

The thing I've been struggling with in terms of reorganization is how and
where to put the stuff the actual tools that we will be creating for each
project. In my case I needed a 2-steps tool with sql2bag and bag2dams that
I called sql2dams and packaged it there at the top level for
lack of other place to do it. The other issue is what Mike already
mentioned, the need to share libraries. It'd be great if we can reorganize
it
thinking on the creations of these tools and their
distribution/installation in different platforms.
Thanks,
Alejandro.

**Comment by robes** [comment]
@bugacov @mikedarcy and I agreed on the following proposed, consolidated structure.

```
iobox
    |- README.md
    |- MANIFEST.in
    |- setup.py
    |- doc
    |    \- this2that.md
    |    \- other docs.md
    |- bin
    |    |- this2that.py
    |    \- other.py
    \- iobox
        |- __init__.py
        |- this2that
        |    |- __init__.py
        |    |- whatever.py
        |    |- data
        |        \- whatever.data.file
        |- client
        |    |- __init__.py
        |    \- whatever.py
        \- bag
             |- __init__.py
             \- whatever.py
```

While there is no one way to structure a Python project, this is a fairly Python-ic style. You'll note the `iobox\iobox\__init__.py` where the package named _iobox_ is under the repo named _iobox_. This always looks a bit redundant but is in fact one of the conventional ways to do it.

We also agreed that we wanted the option to have separate `this2that` packages, in case we want to decompose a module further, and or to have tool-specific `data` subdirectories. Also, there may be more than just the `client` or `bag` packages among the shared packages.

If there are no outstanding commits in master, I could make another `reorg` branch and match this layout.

**Comment by mikedarcy** [comment]
I have an outstanding commit for the dams2bag README.md file which should be finished later today.  If you can wait until tomorrow to rebranch that would be great.
